### ISSUE TITLE
Inline if statements are not supported

### ISSUE THREAD

**Issue by johnmauff** [ROCmSoftwarePlatform/gpufort#31]
The parser does not recognize the follow inlined if-statement:

`          if( tha(i,j,k).gt. 1.0 ) thrad = -1.0/(12.0*3600.0)
`

**Comment by domcharrier** [comment]
Would you mind to recheck with the `develop-acc` branch? 
It appears that this issue was fixed here.

Here, the above single-line statement is correctly converted into the
following multiline statement:
```
if( tha(i,j,k).gt. 1.0 ) then
  thrad = -1.0/(12.0*3600.0)
endif
```

Link to the corresponding test:
https://github.com/ROCmSoftwarePlatform/gpufort/blob/develop-acc/python/test/linemapper/test.linemapper.linemapper.py

**Comment by johnmauff** [comment]
Thank you for your suggestion.  Use of the develop-acc branch did indeed resolve this issue.
